Object subclass: DialogAnswerTypes [
	
	<category: 'IyziForum'>
	<comment: nil>
	
	DialogAnswerTypes class >> okay [
		<category: 'enumeration'>
		
		^'Okay'
	]
	
	DialogAnswerTypes class >> cancel [
		<category: 'enumeration'>
		
		^'Cancel'
	]
	
	DialogAnswerTypes class >> yes [
		<category: 'enumeration'>
		
		^'Yes'
	]
	
	DialogAnswerTypes class >> no [
		<category: 'enumeration'>
		
		^'No'
	]
]
